version: '3.8'

services:
  backend:
    build: .
    container_name: taishare_backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=taishare_db

  db:
    image: mysql:8.0
    container_name: taishare_db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: taishare_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: